import { z } from "zod";
import type { AriaCollection } from "./schemas";
import type { FieldSchema } from "./fieldSchema";

function toInterfaceName(collectionName: string): string {
  return collectionName
    .split(/[-_]/g)
    .filter(Boolean)
    .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
    .join("");
}

function fieldTypeToTs(field: FieldSchema): string {
  switch (field.type) {
    case "string":
    case "text":
    case "slug":
    case "color":
    case "icon":
    case "date":
    case "datetime":
    case "select":
      return "string";
    case "number":
    case "integer":
      return "number";
    case "boolean":
      return "boolean";
    case "multiSelect":
      return "string[]";
    case "image":
    case "file":
      return "{ mediaId: string; alt?: string; publicUrl?: string; src?: string }";
    case "reference":
    case "relation":
      return "string | string[]";
    case "structuredText":
    case "richtext":
      return "unknown[]";
    case "json":
    case "repeater":
    case "object":
    case "link":
      return "Record<string, unknown> | Record<string, unknown>[]";
    default:
      return "unknown";
  }
}

function buildInterfaceFields(
  fields: readonly FieldSchema[],
  indent = 4,
): string[] {
  const pad = " ".repeat(indent);
  return fields.map((field) => {
    const optional = field.required ? "" : "?";
    return `${pad}${field.key}${optional}: ${fieldTypeToTs(field)};`;
  });
}

export function generateAriaEnvDts(
  collections: readonly AriaCollection[],
): string {
  const interfaces = collections
    .map((collection) => {
      const interfaceName = toInterfaceName(collection.name);
      const fields = buildInterfaceFields(collection.schema.fields);
      return `  interface ${interfaceName} {\n${fields.join("\n")}\n  }`;
    })
    .join("\n\n");

  return `// Generated by aria types — do not edit manually.\n\ndeclare namespace AriaCms {\n${interfaces}\n}\n`;
}

export const GenerateAriaEnvDtsInputSchema = z
  .object({
    outFile: z.string().trim().min(1).default("aria-env.d.ts"),
  })
  .strict();

export type GenerateAriaEnvDtsInput = z.infer<
  typeof GenerateAriaEnvDtsInputSchema
>;
