import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { createClient, type InValue } from "@libsql/client/node";
import { beforeEach, describe, expect, it } from "vitest";
import { EmailSecretCipher } from "../../lib/email/crypto";
import { createEmailProvider } from "../../lib/email/providers/factory";
import { SqlEmailRepository, type EmailSqlExecutor } from "../../lib/email/repository";
import { createEmailService, EmailDeliveryService } from "../../lib/email/service";
import { getSystemTemplate } from "../../lib/email/templates";
import type { EmailConnection } from "../../lib/email/types";

function executor(client:ReturnType<typeof createClient>):EmailSqlExecutor{const value=(input:unknown):InValue=>{if(input===null||typeof input==="string"||typeof input==="number"||typeof input==="bigint"||typeof input==="boolean"||input instanceof Uint8Array||input instanceof Date)return input;throw new TypeError("Invalid SQL value");};return{async run(sql,parameters=[]){const result=await client.execute({sql,args:parameters.map(value)});return{changes:result.rowsAffected};},async all(sql,parameters=[]){return(await client.execute({sql,args:parameters.map(value)})).rows;}};}
const key=Buffer.alloc(32,7).toString("base64");
const smtpInput={provider:"smtp" as const,name:"SMTP",enabled:true,fromEmail:"noreply@example.com",config:{host:"smtp.example.com",port:587 as const,security:"starttls" as const,username:"mailer",authMethod:"plain" as const},secret:{password:"secret"}};
const cloudflareInput={provider:"cloudflare_email" as const,name:"Cloudflare Email",enabled:true,fromEmail:"noreply@example.com",config:{accountId:"account",zoneId:"zone",sendingDomain:"example.com"},secret:{apiToken:"token"}};
const smtpConnection:EmailConnection={id:"00000000-0000-4000-8000-000000000001",siteId:"default",name:"SMTP",provider:"smtp",enabled:true,fromEmail:"noreply@example.com",fromName:null,replyToEmail:null,config:smtpInput.config,credentialState:"configured",healthState:"untested",lastCheckedAt:null,lastErrorCode:null,lastErrorMessage:null,createdAt:"2026-01-01T00:00:00.000Z",updatedAt:"2026-01-01T00:00:00.000Z",createdByUserId:null,updatedByUserId:null};

describe("email delivery foundation",()=>{let repository:SqlEmailRepository;let service:EmailDeliveryService;beforeEach(async()=>{const client=createClient({url:":memory:"});await client.executeMultiple(await readFile(resolve(process.cwd(),"aria/migrations/0001_baseline_schema.sql"),"utf8"));repository=new SqlEmailRepository(executor(client));const cipher=new EmailSecretCipher({cfBindings:{ARIA_EMAIL_SECRET_KEY_ID:"v1",ARIA_EMAIL_SECRET_KEY_V1:key}});service=new EmailDeliveryService(repository,cipher,{async publish(){}},"node");});
  it("encrypts with AAD and rejects the wrong boundary",async()=>{const cipher=new EmailSecretCipher({cfBindings:{ARIA_EMAIL_SECRET_KEY_ID:"v1",ARIA_EMAIL_SECRET_KEY_V1:key}});const envelope=await cipher.encryptJson({token:"secret"},"site:a");await expect(cipher.decryptJson(envelope,"site:a",getSystemTemplate("connection_test").variablesSchema)).rejects.toThrow();await expect(cipher.decryptJson(envelope,"site:b",getSystemTemplate("connection_test").variablesSchema)).rejects.toThrow();});
  it("reports missing email encryption key ids with a stable error",async()=>{const cipher=new EmailSecretCipher({cfBindings:{}});await expect(cipher.encryptJson({token:"secret"},"site:a")).rejects.toThrow("EMAIL_KEY_ID_UNAVAILABLE");});
  it("selects the Node SMTP transport without bundling the Worker transport",async()=>{const transport=await createEmailProvider(smtpConnection,{password:"secret"},"node");expect(transport.provider).toBe("smtp");await expect(createEmailProvider(smtpConnection,{password:"secret"},"cloudflare")).rejects.toThrow("EMAIL_SMTP_RUNTIME_MISMATCH");});
  it("bootstraps a managed D1 key when deployment secrets are unavailable",async()=>{const managedService=createEmailService(repository);const connection=await managedService.createConnection("default",{provider:"smtp",name:"SMTP",enabled:true,fromEmail:"noreply@example.com",config:{host:"smtp.example.com",port:587,security:"starttls",username:"mailer",authMethod:"plain"},secret:{password:"secret"}},"admin");expect(connection.credentialState).toBe("configured");expect(await repository.getManagedKey("d1-v1")).toMatchObject({keyId:"d1-v1"});});
  it("processes local development deliveries immediately when no queue binding exists",async()=>{const localService=createEmailService(repository);const connection=await localService.createConnection("default",{provider:"preview",name:"Local preview",enabled:true,fromEmail:"noreply@example.com",config:{},secret:{}},"admin");await localService.replaceRoutes("default","system",[connection.id]);const result=await localService.sendConnectionTest("default",connection.id,"owner@example.com","admin");expect(result.wakeUpPending).toBe(false);expect(result.delivery.status).toBe("accepted");expect(await repository.listAttempts("default",result.delivery.id)).toHaveLength(1);});
  it("sets the first enabled SMTP connection as the default route",async()=>{const connection=await service.createConnection("default",smtpInput,"admin");const routes=await repository.listRoutes("default");expect(routes).toHaveLength(2);expect(routes.map((route)=>route.purpose).sort()).toEqual(["forms","system"]);expect(routes.every((route)=>route.connectionId===connection.id)).toBe(true);});
  it("sets the first enabled Cloudflare Email connection as the default route",async()=>{const connection=await service.createConnection("default",cloudflareInput,"admin");const routes=await repository.listRoutes("default");expect(routes).toHaveLength(2);expect(routes.map((route)=>route.purpose).sort()).toEqual(["forms","system"]);expect(routes.every((route)=>route.connectionId===connection.id)).toBe(true);});
  it("does not overwrite existing routes when adding later connections",async()=>{const first=await service.createConnection("default",smtpInput,"admin");const second=await service.createConnection("default",{...cloudflareInput,name:"Cloudflare fallback",fromEmail:"fallback@example.com"},"admin");const routes=await repository.listRoutes("default");expect(routes).toHaveLength(2);expect(routes.every((route)=>route.connectionId===first.id)).toBe(true);expect(routes.some((route)=>route.connectionId===second.id)).toBe(false);});
  it("does not auto-route disabled connections",async()=>{await service.createConnection("default",{...smtpInput,enabled:false},"admin");expect(await repository.listRoutes("default")).toHaveLength(0);});
  it("validates and escapes system templates",()=>{const template=getSystemTemplate("connection_test"),value=template.variablesSchema.parse({connectionName:"<script>alert(1)</script>",sentAt:new Date().toISOString()}),rendered=template.render(value);expect(rendered.html).toContain("&lt;script&gt;");expect(rendered.html).not.toContain("<script>");expect(rendered.text.length).toBeGreaterThan(0);});
  it("enforces idempotency and completes a preview delivery",async()=>{const connection=await service.createConnection("default",{provider:"preview",name:"Local preview",enabled:true,fromEmail:"noreply@example.com",config:{},secret:{}},"admin");await service.replaceRoutes("default","system",[connection.id]);const input={siteId:"default",purpose:"system" as const,templateKey:"connection_test" as const,variables:{connectionName:"Local preview",sentAt:new Date().toISOString()},to:["owner@example.com"],idempotencyKey:"test:event:1"};const first=await service.enqueueSystem(input),second=await service.enqueueSystem(input);expect(first.created).toBe(true);expect(second.created).toBe(false);expect(second.delivery.id).toBe(first.delivery.id);await service.processDelivery("default",first.delivery.id);const completed=await repository.getDelivery("default",first.delivery.id);expect(completed?.status).toBe("accepted");expect(completed?.payload).toBeNull();expect(await repository.listAttempts("default",first.delivery.id)).toHaveLength(1);});
  it("keeps site-scoped reads isolated",async()=>{await service.createConnection("site-a",{provider:"preview",name:"Preview",enabled:true,fromEmail:"noreply@example.com",config:{},secret:{}},"admin");expect(await repository.listConnections("site-a")).toHaveLength(1);expect(await repository.listConnections("site-b")).toHaveLength(0);});
});
