/**
 * Capability → Astro action operation ID matrix.
 * Used by requireCapability and action gating.
 */

import { z } from "zod";
import { CapabilitySchema, type Capability } from "./types";

/** Stable mutation/read operation identifier (module.action). */
export const OperationIdSchema = z
  .string()
  .regex(
    /^[a-z][a-zA-Z0-9]*(\.[a-z][a-zA-Z0-9]*)+$/u,
    "Expected module.action",
  );
export type OperationId = z.infer<typeof OperationIdSchema>;

const CAPABILITY_OPERATIONS_RAW = {
  editStudioPreferences: ["settings.updateAppearance"],
  editPageContent: [
    "save.page",
    "save.component",
    "save.layout",
    "settings.getComponentGrouping",
    "settings.getMediaGrouping",
    "nodes.mutate",
    "nodes.mutateBatch",
    "nodes.insertNode",
    "nodes.insertNodes",
    "nodes.deleteNode",
    "nodes.replaceNode",
    "nodes.moveNode",
    "nodes.updateClassNames",
    "nodes.addUtilityClass",
    "nodes.removeUtilityClass",
    "nodes.updateCustomClasses",
    "nodes.addCustomClass",
    "nodes.removeCustomClass",
    "crud.getItem",
    "pages.getDetailBundle",
    "crud.updateItem",
    "layouts.updateSlotContent",
    "pages.getVersions",
    "pages.getVersionSnapshot",
    "pages.getPageMedia",
    "pages.saveThumbnail",
    "pages.deleteThumbnail",
    "pages.enqueueThumbnail",
    "components.saveThumbnail",
    "components.deleteThumbnail",
    "components.saveSnapshot",
    "components.getVersions",
    "components.getUsage",
    "localization.getPage",
    "localization.getLayout",
    "localization.savePageDraft",
    "localization.saveLayoutDraft",
  ],
  editPageStructure: [
    "save.page",
    "save.layout",
    "save.component",
    "crud.createItem",
    "crud.updateItem",
    "crud.duplicateItem",
    "layouts.updateSlotContent",
    "ordering.updateOrder",
    "pages.reorderSections",
    "pages.revertVersion",
    "pages.deleteVersion",
  ],
  editPageSeo: [
    "pages.updateSeo",
    "pages.getMeta",
    "pages.cover",
    "pages.removeCover",
    "pages.saveThumbnail",
    "pages.deleteThumbnail",
    "pages.enqueueThumbnail",
    "pages.bulkUpdate",
  ],
  createPages: ["crud.createItem"],
  deletePages: ["crud.deleteItem", "publishing.archive", "pages.removeCover"],
  editPages: [
    "save.page",
    "save.layout",
    "save.component",
    "crud.getItem",
    "crud.createItem",
    "crud.updateItem",
    "crud.deleteItem",
    "crud.duplicateItem",
    "pages.getDetailBundle",
    "layouts.updateSlotContent",
    "ordering.updateOrder",
    "pages.updateSeo",
    "pages.bulkUpdate",
    "pages.listInventory",
    "publishing.unarchive",
    "media.delete",
    "pages.reorderSections",
    "pages.cover",
    "pages.removeCover",
    "nodes.mutate",
    "nodes.mutateBatch",
    "nodes.insertNode",
    "nodes.insertNodes",
    "nodes.deleteNode",
    "nodes.replaceNode",
    "nodes.moveNode",
  ],
  publishContent: [
    "publishing.publish",
    "publishing.batchPublish",
    "publishing.snapshot",
    "cms.entries.publish",
    "localization.publishPage",
    "localization.publishLayout",
  ],
  unpublishContent: [
    "publishing.unpublish",
    "cms.entries.unpublish",
    "cms.entries.archive",
    "localization.unpublishPage",
    "localization.unpublishLayout",
  ],
  reviewContent: [
    "publishing.publish",
    "publishing.unpublish",
    "pages.getDetailBundle",
    "pages.getPageActivity",
    "pages.getPageMedia",
    "cms.workflows.compareRevisions",
    "cms.workflows.getReview",
    "cms.workflows.updateReview",
    "cms.workflows.listAnnotations",
    "cms.workflows.createAnnotation",
    "cms.workflows.resolveAnnotation",
    "cms.workflows.reopenAnnotation",
  ],
  moderateComments: [
    "cms.comments.list",
    "cms.comments.moderate",
    "cms.comments.metrics",
  ],
  editCms: [
    "library.installComponent",
    "library.installPack",
    "library.installStarterButton",
    "library.uninstallPack",
    "settings.getComponentGrouping",
    "settings.getMediaGrouping",
    "cms.collections.list",
    "cms.collections.get",
    "cms.collections.create",
    "cms.collections.update",
    "cms.collections.remove",
    "cms.collections.compileSchema",
    "cms.collections.setTemplate",
    "cms.collections.clearTemplate",
    "cms.entries.list",
    "cms.entries.listCursor",
    "cms.entries.query",
    "cms.entries.get",
    "cms.entries.create",
    "cms.entries.update",
    "cms.entries.remove",
    "cms.workflows.saveAutosave",
    "cms.workflows.getAutosave",
    "cms.workflows.heartbeatPresence",
    "cms.workflows.listPresence",
    "cms.workflows.acquireLock",
    "cms.workflows.releaseLock",
    "cms.revisions.list",
    "cms.revisions.get",
    "cms.revisions.restore",
    "cms.markdownImport.preview",
    "cms.markdownImport.apply",
  ],
  uploadMedia: [
    "media.upload",
    "media.rename",
    "media.duplicate",
    "media.saveProfile",
    "media.replaceSource",
    "media.saveTransformVariant",
    "media.deleteTransformVariant",
  ],
  useMediaLibrary: ["media.list", "media.usages", "media.getTransformState"],
  syncMedia: [
    "media.rebuildUsageIndex",
    "media.sync.plan",
    "media.sync.apply",
    "media.sync.history",
    "contentSync.plan",
    "contentSync.apply",
    "contentSync.status",
    "contentSync.history",
    "importExport.exportItem",
    "importExport.exportAll",
    "siteExport.create",
  ],
  editSiteSettings: [
    "settings.get",
    "settings.update",
    "settings.updateAppearance",
    "settings.updateIcons",
    "settings.updateComponentGrouping",
    "settings.updateMediaGrouping",
    "settings.reset",
    "designSystem.saveColors",
    "designSystem.saveTypography",
    "designSystem.saveGlobalStyles",
    "designSystem.saveBreakpoints",
    "designSystem.applyTemplate",
    "designSystem.import",
    "designSystem.importBundle",
    "styles.update",
    "styles.createClass",
    "styles.updateClassRule",
    "styles.deleteClass",
    "styles.deleteClasses",
    "styles.renameClass",
    "styles.duplicateClass",
    "styles.setAuthoringMode",
    "styles.setFrameworkMode",
    "styles.bulkImportClasses",
    "styles.removeClassRule",
    "styles.updateClassPseudoRule",
    "styles.removeClassPseudoRule",
    "styles.updateClassUsage",
    "styles.regenerateGlobalCSS",
    "fonts.uploadCustom",
    "fonts.deleteCustom",
    "fonts.renameCustom",
    "fonts.enableGoogle",
    "fonts.disableGoogle",
    "fonts.updateGoogleVariants",
  ],
  editDiscoverySettings: [
    "settings.updateDiscovery",
    "discovery.getReport",
    "discovery.getArtifacts",
    "discovery.getGeneratedBaseline",
  ],
  viewDiscoverySettings: [
    "settings.get",
    "discovery.getReport",
    "discovery.getArtifacts",
    "discovery.getGeneratedBaseline",
  ],
  manageRedirects: [
    "redirects.list",
    "redirects.listTargets",
    "redirects.create",
    "redirects.update",
    "redirects.delete",
    "redirects.flattenChain",
    "redirects.importCsv",
  ],
  viewRedirects: ["redirects.list"],
  editAnalytics: ["settings.update", "analytics.getMetricsAvailability"],
  viewStudioMetrics: [
    "analytics.getMetricsAvailability",
    "analytics.getSiteTraffic",
    "analytics.getPagesTraffic",
    "analytics.getPageTraffic",
  ],
  editDomains: ["settings.update"],
  editCustomCode: ["settings.update"],
  manageUsers: [
    "auth.listUsers",
    "auth.createUser",
    "auth.updateUser",
    "auth.deleteUser",
    "auth.resetUserPassword",
    "auth.uploadAvatar",
    "auth.removeAvatar",
  ],
  manageRoles: ["auth.updateUser", "auth.createUser"],
  manageSecurity: [
    "auth.updateCaptchaConfig",
    "auth.getCaptchaConfig",
    "auth.createTurnstileWidget",
    "auth.getTwoFactorPolicy",
    "auth.updateTwoFactorPolicy",
    "auth.adminInitTotp",
    "auth.adminEnableTotp",
    "auth.adminDisableTotp",
    "auth.adminRegenerateBackupCodes",
    "pages.updatePolicy",
    "pages.getPolicy",
    "pages.verifyAccessPassword",
  ],
  manageExports: [
    "importExport.list",
    "importExport.exportItem",
    "importExport.exportAll",
    "siteExport.create",
    "siteExport.list",
    "siteExport.getLatest",
    "siteExport.delete",
    "designSystem.export",
    "wordpressImport.upload",
    "wordpressImport.analyze",
    "wordpressImport.plan",
    "wordpressImport.apply",
    "wordpressImport.cancel",
    "wordpressImport.getBatch",
    "wordpressImport.getEvents",
    "wordpressImport.listBatches",
    "wordpressImport.getReport",
    "wordpressImport.deleteBatch",
    "wordpressImport.cleanupExpiredFiles",
  ],
  manageBackups: ["siteExport.create", "siteExport.delete"],
  manageIntegrations: [
    "settings.update",
    "deployments.trigger",
    "webhooks.list",
    "webhooks.status",
    "webhooks.create",
    "webhooks.rotateSecret",
    "webhooks.updateSubscriptions",
    "webhooks.setStatus",
    "webhooks.deliveryOverview",
    "webhooks.listDeliveries",
    "webhooks.retryDelivery",
  ],
  manageApiTokens: [
    "apiTokens.list",
    "apiTokens.create",
    "apiTokens.revoke",
    "apiTokens.remove",
  ],
  viewEmailDelivery: [
    "email.connections.list",
    "email.connections.get",
    "email.routes.list",
    "email.outbox.overview",
    "email.outbox.list",
    "email.outbox.get",
    "email.outbox.attempts",
  ],
  manageEmailDelivery: [
    "email.connections.create",
    "email.connections.update",
    "email.connections.replaceSecret",
    "email.connections.delete",
    "email.connections.verify",
    "email.connections.sendTest",
    "email.routes.replacePurpose",
    "email.outbox.cancel",
    "email.outbox.retry",
    "email.outbox.drainLocal",
  ],
  manageBilling: [
    "settings.update",
    "agent.saveAiQuotaPolicy",
    "agent.deleteAiQuotaPolicy",
  ],
  useStudioAgent: [
    "agent.getAvailability",
    "agent.getChatHistory",
    "agent.chat",
    "agent.clearChat",
    "agent.readSite",
    "crud.getItem",
    "pages.listInventory",
    "agent.createMcpTokenPersonal",
    "agent.listPersonalMcpTokens",
    "agent.revokePersonalMcpToken",
    "agent.updatePersonalMcpToken",
    "agent.confirmAction",
    "agent.undoMutation",
  ],
  editAgentSettings: [
    "settings.updateAgent",
    "settings.updateAgentProvider",
    "settings.removeAgentProvider",
    "settings.removeInferenceProvider",
    "agent.createMcpToken",
    "agent.revokeMcpToken",
    "agent.listMcpTokens",
    "agent.updateMcpToken",
    "agent.listActivityLog",
    "agent.createExternalMcpConnection",
    "agent.updateExternalMcpConnection",
    "agent.deleteExternalMcpConnection",
    "agent.discoverExternalMcpConnection",
  ],
  viewAgentSettings: [
    "settings.get",
    "agent.getAvailability",
    "agent.listWorkersAiModels",
    "agent.listOpencodeModels",
    "agent.listOpenAiModels",
    "agent.listAnthropicModels",
    "agent.listGoogleModels",
    "agent.listOpenRouterModels",
    "agent.listMcpTokens",
    "agent.listExternalMcpConnections",
    "agent.listAiQuotaPolicies",
  ],
} as const satisfies Record<Capability, readonly OperationId[]>;

function assertCompleteCapabilityMap(
  map: Record<Capability, readonly OperationId[]>,
): Record<Capability, readonly OperationId[]> {
  const capabilities = CapabilitySchema.options;
  for (const capability of capabilities) {
    const operations = map[capability];
    if (!operations?.length) {
      throw new Error(
        `CAPABILITY_OPERATIONS missing operations for: ${capability}`,
      );
    }
    for (const operation of operations) {
      OperationIdSchema.parse(operation);
    }
  }
  return map;
}

export const CAPABILITY_OPERATIONS = assertCompleteCapabilityMap(
  CAPABILITY_OPERATIONS_RAW,
);

const CapabilityOperationsRecordSchema = z.record(
  CapabilitySchema,
  z.array(OperationIdSchema).readonly(),
);

/** Parsed view for runtime validation at boundaries. */
export const CapabilityOperationsRecordSchemaExport =
  CapabilityOperationsRecordSchema;

export function getOperationsForCapability(
  capability: Capability,
): readonly OperationId[] {
  const parsedCapability = CapabilitySchema.parse(capability);
  return CAPABILITY_OPERATIONS[parsedCapability];
}

export function getCapabilitiesForOperation(
  operationId: OperationId,
): Capability[] {
  const parsedOperation = OperationIdSchema.parse(operationId);
  const matches: Capability[] = [];
  for (const capability of CapabilitySchema.options) {
    if (CAPABILITY_OPERATIONS[capability].includes(parsedOperation)) {
      matches.push(capability);
    }
  }
  return matches;
}
