/**
 * Canonical authorship contracts — storage targets and legacy projections.
 */

export {
  VERSION_AUTHORSHIP_COLUMNS,
  VERSIONED_ASSET_META,
  SINGLETON_AUTHORSHIP_TABLES,
  ASSET_ROW_AUTHORSHIP_COLUMNS,
  MEDIA_ASSET_DELETE_AUTHORSHIP_COLUMNS,
  NON_CANONICAL_AUTHORSHIP_TABLES,
  MEDIA_LOCATIONS_AUTHORSHIP_NOTE,
  AUTHORSHIP_STORAGE_TARGETS,
  type VersionAuthorshipColumn,
  type VersionedAssetKind,
  type SingletonAuthorshipTable,
} from "./storageTargets";

export {
  ALL_AUTHORSHIP_COLUMN_NAMES,
  AuthorshipColumnNameSchema,
  AuthorshipColumnTargetSchema,
  AuthorshipColumnTargetsSchema,
  AuthorshipMigrationContextSchema,
  AuthorshipTableNameSchema,
  SingletonAuthorshipTableSchema,
  VersionAuthorshipTableSchema,
  VERSION_AUTHORSHIP_TABLES,
  applyAuthorshipBackfill,
  applyAuthorshipColumnMigrations,
  buildAlterTableAddColumnStatement,
  buildCreateTableAuthorshipColumnDefs,
  getAuthorshipBackfillStatements,
  getAuthorshipColumnTargets,
  getAuthorshipColumnsForTable,
  getAuthorshipMigrationStatements,
  getSingletonUpdatedByBackfillStatements,
  getVersionAuthorshipBackfillStatements,
  isIgnorableAuthorshipMigrationError,
  type AuthorshipColumnName,
  type AuthorshipColumnTarget,
  type AuthorshipMigrationContext,
  type AuthorshipTableName,
  type VersionAuthorshipTable,
} from "./schemaMigrations";

export {
  LegacyAuthorProjectionSchema,
  LegacyContributorProjectionSchema,
  VersionRowAuthorshipSliceSchema,
  DeriveAssetAuthorshipInputSchema,
  toLegacyAuthorProjection,
  fromLegacyAuthorProjection,
  deriveAssetAuthorship,
  parseAssetAuthorship,
  type LegacyAuthorProjection,
  type LegacyContributorProjection,
  type VersionRowAuthorshipSlice,
  type DeriveAssetAuthorshipInput,
} from "./projections";

export {
  PageInventoryAuthorshipSchema,
  PageVersionAuthorshipEntrySchema,
  parsePageInventoryAuthorship,
  parsePageVersionAuthorshipEntry,
  toPageInventoryAuthorship,
  type PageInventoryAuthorship,
  type PageVersionAuthorshipEntry,
} from "./schemas";

export {
  VersionAuthorshipRowSchema,
  LegacyDslAuthorshipFieldsSchema,
  formatActorDisplayName,
  parseActorFromSqlColumns,
  parseVersionAuthorshipRow,
  buildDeriveAssetAuthorshipInput,
  parseLegacyDslAuthorshipFields,
  mergeAuthorshipWithLegacyDsl,
  hydratePageDslAuthorship,
  resolvePageAuthorship,
  type VersionAuthorshipRow,
  type LegacyDslAuthorshipFields,
} from "./reads";

export {
  STAMPING_VERSION_COLUMN_NAMES,
  STAMPING_ASSET_ROW_COLUMN_NAMES,
  STAMPING_MEDIA_DELETE_COLUMN_NAMES,
  actorRefToSqlBindings,
  appendSqlFragment,
  assertNoVersionAuthorshipUpdateSql,
  buildAuthorshipSaveContext,
  buildDesignSystemRowInsertAuthorship,
  buildMediaAuthorshipContext,
  buildMediaAuthorshipContextFromSession,
  buildMediaAuthorshipPatch,
  buildMediaAssetInsertAuthorship,
  appendMediaAuthorshipUpdateSets,
  buildSingletonUpsertAuthorshipAssignments,
  buildSystemAuthorshipSaveContext,
  buildVersionInsertAuthorshipColumns,
  parseAuthorshipSaveContext,
  parseOptionalAuthorshipSaveContext,
  parsePermissionProfileFromStorage,
  resolveUserPermissionProfile,
  resolveVersionAuthorshipForSave,
  rolePresetFromUserRole,
  sessionUserToActorRef,
  type ActorSqlBindings,
  type MediaAuthorshipMutationKind,
  type SingletonAuthorshipInsert,
  type SingletonAuthorshipUpdate,
  type SqlFragment,
} from "./stamping";
