/** Generated by npm run build:icons. */
export const ICON_ASSET_SCHEMA_VERSION = 1 as const;
export const ICON_SNAPSHOT_VERSION = "84a53bf7bfdf0f24d6a8" as const;
export const ICON_ASSET_BASE_PATH = "/vendor/aria-icons/v1/84a53bf7bfdf0f24d6a8" as const;
