import type { ComponentDSL } from "../../types/nodes";
import { BUTTON_VARIANT_OPTIONS } from "../../blocks/buttonVariants";

export const ARIA_FREE_BUTTON_COMPONENT: ComponentDSL = {
  id: "button",
  name: "Button",
  title: "Button",
  description:
    "Reusable action button with curated variants and accessibility defaults.",
  category: "button",
  source: "aria",
  packId: "aria-free-pack",
  tier: "free",
  isLocked: true,
  version: "1.0.0",
  updatedAt: "2026-02-24T00:00:00.000Z",
  propSchema: [
    {
      name: "variant",
      type: "select",
      label: "Variant",
      section: "Appearance",
      default: "primary",
      visual: true,
      options: BUTTON_VARIANT_OPTIONS.map((option) => ({
        value: option.value,
        label: option.label,
      })),
    },
    {
      name: "size",
      type: "select",
      label: "Size",
      section: "Appearance",
      default: "default",
      visual: true,
      options: [
        { value: "sm", label: "Small" },
        { value: "default", label: "Default" },
        { value: "lg", label: "Large" },
        { value: "icon", label: "Icon" },
      ],
    },
    {
      name: "label",
      type: "text",
      label: "Button Text",
      section: "Content",
      default: "Button",
      required: true,
      maxLength: 120,
    },
    {
      name: "icon",
      type: "icon",
      label: "Icon",
      section: "Content",
      description: "Optional icon for the button",
      iconSet: "lucide",
    },
    {
      name: "iconPosition",
      type: "select",
      label: "Icon Position",
      section: "Content",
      default: "left",
      condition: { field: "icon", operator: "notEmpty" },
      options: [
        { value: "left", label: "Left" },
        { value: "right", label: "Right" },
      ],
    },
    {
      name: "iconGap",
      type: "text",
      label: "Icon Gap",
      section: "Content",
      default: "0.5rem",
      condition: { field: "icon", operator: "notEmpty" },
    },
    {
      name: "iconSpaceBetween",
      type: "boolean",
      label: "Space Between",
      section: "Content",
      default: false,
      condition: { field: "icon", operator: "notEmpty" },
    },
    {
      name: "iconSize",
      type: "text",
      label: "Icon Size",
      section: "Content",
      default: "1em",
      placeholder: "1em",
      condition: { field: "icon", operator: "notEmpty" },
    },
    {
      name: "iconColor",
      type: "color",
      label: "Icon Color",
      section: "Content",
      default: "color-mix(in srgb, var(--color-foreground) 80%, transparent)",
      condition: { field: "icon", operator: "notEmpty" },
    },
    {
      name: "disabled",
      type: "boolean",
      label: "Disabled",
      section: "Behavior",
      default: false,
    },
    {
      name: "href",
      type: "url",
      label: "URL",
      section: "Behavior",
      description: "Optional navigation URL",
    },
    {
      name: "ariaLabel",
      type: "text",
      label: "Aria Label",
      section: "Accessibility",
      description: "Accessible label. Falls back to Button Text when empty.",
    },
  ],
  nodes: [
    {
      id: "button-root",
      type: "Button",
      props: {
        label: "Button",
        variant: "primary",
        size: "default",
        disabled: false,
      },
      styles: {},
      a11y: {
        role: "button",
      },
      classNames: {
        base: [
          "inline-flex",
          "items-center",
          "justify-center",
          "rounded-md",
          "bg-primary",
          "px-4",
          "py-2.5",
          "text-sm",
          "font-semibold",
          "text-primary-foreground",
          "shadow-sm",
          "hover:opacity-90",
          "focus-visible:outline-none",
          "focus-visible:ring-2",
          "focus-visible:ring-ring",
          "focus-visible:ring-offset-2",
          "transition-all",
        ],
      },
      children: [],
    },
  ],
  slots: [],
};
