import { z } from "zod";
import type { ConnectionVerification, EmailProviderTransport, ProviderSendOutcome, RenderedEmailMessage } from "./types";

const CloudflareSendResponseSchema = z.object({ success: z.boolean(), errors: z.array(z.object({ code: z.union([z.string(),z.number()]).transform(String), message: z.string() })).default([]), result: z.object({ delivered: z.array(z.email()).default([]), permanent_bounces: z.array(z.email()).default([]), queued: z.array(z.email()).default([]), message_id: z.string().optional() }).optional() });
export class CloudflareEmailTransport implements EmailProviderTransport {
  readonly provider = "cloudflare_email" as const;
  constructor(private readonly accountId:string,private readonly zoneId:string,private readonly sendingDomain:string,private readonly apiToken:string){}
  async verify():Promise<ConnectionVerification>{
    try{const response=await fetch(`https://api.cloudflare.com/client/v4/zones/${encodeURIComponent(this.zoneId)}/email/sending/subdomains`,{headers:{Authorization:`Bearer ${this.apiToken}`}});if(!response.ok)return{ok:false,code:`HTTP_${response.status}`,message:"Cloudflare email domain verification failed"};return{ok:true,message:`Cloudflare access verified for ${this.sendingDomain}`};}catch{return{ok:false,code:"NETWORK",message:"Cloudflare email verification could not connect"};}
  }
  async send(message:RenderedEmailMessage):Promise<ProviderSendOutcome>{
    try{const response=await fetch(`https://api.cloudflare.com/client/v4/accounts/${encodeURIComponent(this.accountId)}/email/sending/send`,{method:"POST",headers:{Authorization:`Bearer ${this.apiToken}`,"Content-Type":"application/json"},body:JSON.stringify({from:{address:message.from,name:message.fromName},to:message.to,cc:message.cc,bcc:message.bcc,reply_to:message.replyTo,subject:message.subject,html:message.html,text:message.text})});const parsed=CloudflareSendResponseSchema.safeParse(await response.json());if(!parsed.success)return{kind:response.status>=500?"transient_failure":"permanent_failure",code:"INVALID_PROVIDER_RESPONSE",errorClass:"provider",message:"Cloudflare returned an invalid response"};if(!response.ok||!parsed.data.success){const error=parsed.data.errors[0];const transient=response.status===429||response.status>=500;return{kind:transient?"transient_failure":"permanent_failure",code:error?.code??`HTTP_${response.status}`,errorClass:response.status===429?"rate_limit":response.status===401?"authentication":"provider",message:error?.message??"Cloudflare email send failed"};}const result=parsed.data.result;if(!result)return{kind:"permanent_failure",code:"MISSING_RESULT",errorClass:"provider",message:"Cloudflare response omitted result"};if(result.permanent_bounces.length>0)return{kind:"permanent_failure",code:"PERMANENT_BOUNCE",errorClass:"recipient",message:"Cloudflare rejected one or more recipients"};return{kind:result.queued.length>0?"queued_by_provider":"accepted",messageId:result.message_id,metadata:{delivered:result.delivered.length,queued:result.queued.length}};}catch{return{kind:"transient_failure",code:"NETWORK",errorClass:"network",message:"Cloudflare email request failed"};}
  }
}
