import { connect, type CloudflareSocket } from "cloudflare:sockets";
import type { z } from "zod";
import type { SmtpConfigSchema } from "../types";
import type { ConnectionVerification, EmailProviderTransport, ProviderSendOutcome, RenderedEmailMessage } from "./types";

type SmtpConfig = z.infer<typeof SmtpConfigSchema>;
type Reply = Readonly<{ code:number; lines:string[] }>;
const encoder=new TextEncoder();
function withTimeout<T>(promise:Promise<T>,milliseconds=30_000):Promise<T>{return Promise.race([promise,new Promise<T>((_,reject)=>setTimeout(()=>reject(new Error("SMTP_TIMEOUT")),milliseconds))]);}
function base64(value:string):string{let binary="";for(const byte of new TextEncoder().encode(value))binary+=String.fromCharCode(byte);return btoa(binary);}
function cleanHeader(value:string):string{if(/[\r\n]/u.test(value))throw new Error("SMTP_HEADER_INJECTION");return value;}
function dotStuff(value:string):string{return value.replaceAll(/(^|\r\n)\./gu,"$1..");}

class SmtpSession {
  private reader:ReadableStreamDefaultReader<Uint8Array>;
  private writer:WritableStreamDefaultWriter<Uint8Array>;
  private buffer="";
  constructor(private socket:CloudflareSocket){this.reader=socket.readable.getReader();this.writer=socket.writable.getWriter();}
  async close():Promise<void>{try{this.reader.releaseLock();this.writer.releaseLock();await this.socket.close();}catch{/* already closed */}}
  async startTls():Promise<void>{this.reader.releaseLock();this.writer.releaseLock();this.socket=this.socket.startTls();this.reader=this.socket.readable.getReader();this.writer=this.socket.writable.getWriter();this.buffer="";}
  async command(command?:string):Promise<Reply>{if(command!==undefined)await withTimeout(this.writer.write(encoder.encode(`${command}\r\n`)));const lines:string[]=[];let code=0;for(;;){const line=await this.readLine();const match=/^(\d{3})([ -])(.*)$/u.exec(line);if(!match)throw new Error("SMTP_MALFORMED_REPLY");const parsed=Number(match[1]);if(code===0)code=parsed;if(parsed!==code)throw new Error("SMTP_INCONSISTENT_REPLY");lines.push(match[3]??"");if(match[2]===" ")return{code,lines};if(lines.length>100)throw new Error("SMTP_REPLY_TOO_LARGE");}}
  private async readLine():Promise<string>{for(;;){const index=this.buffer.indexOf("\r\n");if(index>=0){const line=this.buffer.slice(0,index);this.buffer=this.buffer.slice(index+2);return line;}const result=await withTimeout(this.reader.read());if(result.done)throw new Error("SMTP_CONNECTION_CLOSED");this.buffer+=new TextDecoder().decode(result.value,{stream:true});if(this.buffer.length>65_536)throw new Error("SMTP_REPLY_TOO_LARGE");}}
}

export class WorkerSmtpTransport implements EmailProviderTransport {
  readonly provider="smtp" as const;
  constructor(private readonly config:SmtpConfig,private readonly password:string){}
  private async open():Promise<SmtpSession>{const session=new SmtpSession(connect({hostname:this.config.host,port:this.config.port},{secureTransport:this.config.security==="tls"?"on":"starttls",allowHalfOpen:false}));const greeting=await session.command();if(greeting.code!==220)throw new Error(`SMTP_${greeting.code}`);let ehlo=await session.command("EHLO aria.local");if(ehlo.code!==250)throw new Error(`SMTP_${ehlo.code}`);if(this.config.security==="starttls"){if(!ehlo.lines.some((line)=>line.toUpperCase().startsWith("STARTTLS")))throw new Error("SMTP_STARTTLS_UNAVAILABLE");const start=await session.command("STARTTLS");if(start.code!==220)throw new Error(`SMTP_${start.code}`);await session.startTls();ehlo=await session.command("EHLO aria.local");if(ehlo.code!==250)throw new Error(`SMTP_${ehlo.code}`);}if(this.config.authMethod==="plain"){const auth=await session.command(`AUTH PLAIN ${base64(`\u0000${this.config.username}\u0000${this.password}`)}`);if(auth.code!==235)throw new Error(`SMTP_${auth.code}`);}else{let auth=await session.command("AUTH LOGIN");if(auth.code!==334)throw new Error(`SMTP_${auth.code}`);auth=await session.command(base64(this.config.username));if(auth.code!==334)throw new Error(`SMTP_${auth.code}`);auth=await session.command(base64(this.password));if(auth.code!==235)throw new Error(`SMTP_${auth.code}`);}return session;}
  async verify():Promise<ConnectionVerification>{let session:SmtpSession|undefined;try{session=await this.open();await session.command("QUIT");return{ok:true,message:"SMTP TLS and authentication verified"};}catch{return{ok:false,code:"SMTP_VERIFY_FAILED",message:"SMTP verification failed"};}finally{await session?.close();}}
  async send(message:RenderedEmailMessage):Promise<ProviderSendOutcome>{let session:SmtpSession|undefined;try{session=await this.open();let reply=await session.command(`MAIL FROM:<${cleanHeader(message.from)}>`);if(reply.code!==250)throw new Error(`SMTP_${reply.code}`);for(const recipient of [...message.to,...message.cc,...message.bcc]){reply=await session.command(`RCPT TO:<${cleanHeader(recipient)}>`);if(reply.code>=400)throw new Error(`SMTP_${reply.code}`);}reply=await session.command("DATA");if(reply.code!==354)throw new Error(`SMTP_${reply.code}`);const boundary=`aria-${message.deliveryId}`;const headers=[`From: ${message.fromName?`${cleanHeader(message.fromName)} <${message.from}>`:message.from}`,`To: ${message.to.join(", ")}`,message.cc.length?`Cc: ${message.cc.join(", ")}`:null,message.replyTo?`Reply-To: ${cleanHeader(message.replyTo)}`:null,`Subject: ${cleanHeader(message.subject)}`,`Message-ID: <${message.deliveryId}@${message.from.split("@")[1]}>`,`Date: ${new Date().toUTCString()}`,"MIME-Version: 1.0",`Content-Type: multipart/alternative; boundary="${boundary}"`].filter((value):value is string=>value!==null);const body=[`--${boundary}`,'Content-Type: text/plain; charset="UTF-8"',"Content-Transfer-Encoding: 8bit","",message.text,`--${boundary}`,'Content-Type: text/html; charset="UTF-8"',"Content-Transfer-Encoding: 8bit","",message.html,`--${boundary}--`,""].join("\r\n");reply=await session.command(`${headers.join("\r\n")}\r\n\r\n${dotStuff(body)}\r\n.`);if(reply.code!==250)throw new Error(`SMTP_${reply.code}`);await session.command("QUIT");return{kind:"accepted",messageId:`${message.deliveryId}@${message.from.split("@")[1]}`};}catch(error){const text=error instanceof Error?error.message:"SMTP_UNKNOWN";const match=/SMTP_(\d{3})/u.exec(text);const code=match?Number(match[1]):0;return{kind:code>=400&&code<500?"transient_failure":"permanent_failure",code:code?`SMTP_${code}`:"SMTP_SEND_FAILED",errorClass:code===535?"authentication":code>=500?"provider":"network",message:"SMTP delivery failed"};}finally{await session?.close();}}
}
