import { z } from "zod";
import { getCloudflareEnv, type RuntimeLocals } from "../cloudflare/env";
import { connectionSecretAad, deliveryPayloadAad, EmailSecretCipher } from "./crypto";
import type { ConnectionInsert, DeliveryInsert, EmailRepository, PaginatedDeliveries } from "./repository";
import { createEmailProvider } from "./providers/factory";
import type { ConnectionVerification, ProviderSendOutcome } from "./providers/types";
import { getSystemTemplate } from "./templates";
import {
  CloudflareEmailConfigSchema, CloudflareEmailSecretSchema, DeliveryListQuerySchema,
  EmailAddressListSchema, EmailConnectionCreateSchema, EmailPurposeSchema, PreviewSecretSchema,
  SmtpConfigSchema, SmtpSecretSchema, type DeliveryListQuery, type EmailAttempt, type EmailConnection,
  type EmailConnectionCreate, type EmailDelivery, type EmailPurpose, type EmailRoute,
} from "./types";

const EnqueueInputSchema=z.object({siteId:z.string().min(1),purpose:EmailPurposeSchema,templateKey:z.enum(["password_reset","connection_test","form_submission_notification"]),variables:z.unknown(),to:EmailAddressListSchema.min(1),cc:EmailAddressListSchema.optional(),bcc:EmailAddressListSchema.optional(),idempotencyKey:z.string().min(1).max(500),createdByUserId:z.string().optional()}).superRefine((value,context)=>{if(value.to.length+(value.cc?.length??0)+(value.bcc?.length??0)>50)context.addIssue({code:"custom",message:"At most 50 recipients are allowed"});});
const MANAGED_EMAIL_KEY_ID = "d1-v1";
export type EnqueueSystemEmailInput=z.infer<typeof EnqueueInputSchema>;
export type EnqueueResult=Readonly<{delivery:EmailDelivery;created:boolean;wakeUpPending:boolean}>;
export interface EmailQueuePublisher { publish(message:Readonly<{version:1;siteId:string;deliveryId:string}>):Promise<void>; }

function randomKeyBase64(): string { const bytes=crypto.getRandomValues(new Uint8Array(32)); let binary=""; for(const byte of bytes) binary+=String.fromCharCode(byte); return btoa(binary); }
function addDays(date:Date,days:number):string{return new Date(date.getTime()+days*86_400_000).toISOString();}
function addMilliseconds(date:Date,milliseconds:number):string{return new Date(date.getTime()+milliseconds).toISOString();}
function secretSchema(provider:EmailConnection["provider"]):z.ZodType<unknown>{if(provider==="cloudflare_email")return CloudflareEmailSecretSchema;if(provider==="smtp")return SmtpSecretSchema;return PreviewSecretSchema;}
function safeMessage(error:unknown):string{return error instanceof Error&&error.message.startsWith("EMAIL_")?error.message:"Email operation failed";}

export class EmailDeliveryService {
  constructor(private readonly repository:EmailRepository,private readonly cipher:EmailSecretCipher,private readonly publisher:EmailQueuePublisher,private readonly runtime:"node"|"cloudflare"){}
  listConnections(siteId:string):Promise<EmailConnection[]>{return this.repository.listConnections(siteId);}
  getConnection(siteId:string,id:string):Promise<EmailConnection|null>{return this.repository.getConnection(siteId,id);}
  listRoutes(siteId:string):Promise<EmailRoute[]>{return this.repository.listRoutes(siteId);}
  listDeliveries(siteId:string,query:DeliveryListQuery):Promise<PaginatedDeliveries>{return this.repository.listDeliveries(siteId,DeliveryListQuerySchema.parse(query));}
  getDelivery(siteId:string,id:string):Promise<EmailDelivery|null>{return this.repository.getDelivery(siteId,id);}
  getAttempts(siteId:string,id:string):Promise<EmailAttempt[]>{return this.repository.listAttempts(siteId,id);}
  getOverview(siteId:string):Promise<Record<string,number>>{return this.repository.getOverview(siteId);}

  async createConnection(siteId:string,input:EmailConnectionCreate,actorId:string):Promise<EmailConnection>{const parsed=EmailConnectionCreateSchema.parse(input);if(parsed.provider==="preview"&&this.runtime!=="node")throw new Error("EMAIL_PREVIEW_NODE_ONLY");const now=new Date().toISOString(),id=crypto.randomUUID();const record:ConnectionInsert={id,siteId,name:parsed.name,provider:parsed.provider,enabled:parsed.enabled,fromEmail:parsed.fromEmail,fromName:parsed.fromName??null,replyToEmail:parsed.replyToEmail??null,config:parsed.config,createdAt:now,updatedAt:now,createdByUserId:actorId,updatedByUserId:actorId};const connection=await this.repository.createConnection(record);try{if(parsed.provider!=="preview"){const envelope=await this.cipher.encryptJson(parsed.secret,connectionSecretAad(siteId,id,parsed.provider));await this.repository.saveConnectionSecret(siteId,id,envelope);}if(parsed.enabled&&parsed.provider!=="preview"){await this.ensureDefaultRoutes(siteId,id);}return(await this.repository.getConnection(siteId,id))??connection;}catch(error){await this.repository.deleteConnection(siteId,id);throw error;}}
  async updateConnection(siteId:string,id:string,patch:unknown,actorId:string):Promise<EmailConnection>{const existing=await this.mustConnection(siteId,id);const common=z.object({name:z.string().trim().min(1).max(100).optional(),enabled:z.boolean().optional(),fromEmail:z.email().optional(),fromName:z.string().trim().max(100).nullable().optional(),replyToEmail:z.email().nullable().optional(),config:z.unknown().optional()}).parse(patch);const config=common.config===undefined?existing.config:existing.provider==="cloudflare_email"?CloudflareEmailConfigSchema.parse(common.config):existing.provider==="smtp"?SmtpConfigSchema.parse(common.config):z.object({outputDirectory:z.string().optional()}).parse(common.config);const updated=await this.repository.updateConnection(siteId,id,{name:common.name??existing.name,enabled:common.enabled??existing.enabled,fromEmail:common.fromEmail??existing.fromEmail,fromName:common.fromName===undefined?existing.fromName:common.fromName,replyToEmail:common.replyToEmail===undefined?existing.replyToEmail:common.replyToEmail,config,updatedByUserId:actorId});if(!updated)throw new Error("EMAIL_CONNECTION_NOT_FOUND");return updated;}
  async replaceSecret(siteId:string,id:string,value:unknown):Promise<void>{const connection=await this.mustConnection(siteId,id);if(connection.provider==="preview")throw new Error("EMAIL_PREVIEW_HAS_NO_SECRET");const secret=secretSchema(connection.provider).parse(value),envelope=await this.cipher.encryptJson(secret,connectionSecretAad(siteId,id,connection.provider));await this.repository.saveConnectionSecret(siteId,id,envelope);}
  async deleteConnection(siteId:string,id:string):Promise<boolean>{return this.repository.deleteConnection(siteId,id);}
  async replaceRoutes(siteId:string,purpose:EmailPurpose,ids:readonly string[]):Promise<EmailRoute[]>{const parsedPurpose=EmailPurposeSchema.parse(purpose),unique=[...new Set(z.array(z.uuid()).parse(ids))];for(const id of unique){const connection=await this.mustConnection(siteId,id);if(!connection.enabled)throw new Error("EMAIL_CONNECTION_DISABLED");}return this.repository.replacePurposeRoutes(siteId,parsedPurpose,unique);}
  async verifyConnection(siteId:string,id:string):Promise<ConnectionVerification>{const connection=await this.mustConnection(siteId,id);try{const transport=await this.transport(siteId,connection),result=await transport.verify();await this.repository.updateConnectionHealth(siteId,id,result.ok?"healthy":"failed",result.code,result.ok?undefined:result.message);return result;}catch(error){const message=safeMessage(error);await this.repository.updateConnectionHealth(siteId,id,"failed","EMAIL_CONNECTION_INVALID",message);return{ok:false,code:"EMAIL_CONNECTION_INVALID",message};}}
  async sendConnectionTest(siteId:string,id:string,to:string,actorId:string):Promise<EnqueueResult>{const connection=await this.mustConnection(siteId,id);if(!connection.enabled)throw new Error("EMAIL_CONNECTION_DISABLED");const now=new Date();const template=getSystemTemplate("connection_test");const variables={connectionName:connection.name,sentAt:now.toISOString()};const parsed=template.variablesSchema.parse(variables);const deliveryId=crypto.randomUUID(),payload=await this.cipher.encryptJson(parsed,deliveryPayloadAad(siteId,deliveryId,template.key,template.version));const inserted=await this.repository.enqueueDelivery({id:deliveryId,siteId,purpose:"system",templateKey:template.key,templateVersion:template.version,connectionId:id,to:[z.email().parse(to)],cc:[],bcc:[],payload,idempotencyKey:`email:test:${crypto.randomUUID()}`,maxAttempts:1,nextAttemptAt:now.toISOString(),createdByUserId:actorId,createdAt:now.toISOString(),updatedAt:now.toISOString(),payloadPurgeAt:addDays(now,7),metadataPurgeAt:addDays(now,30)});return this.publish(inserted.delivery,inserted.created);}
  async enqueueSystem(input:EnqueueSystemEmailInput):Promise<EnqueueResult>{const parsed=EnqueueInputSchema.parse(input);const routes=await this.repository.resolvePurposeConnections(parsed.siteId,parsed.purpose);if(routes.length===0)throw new Error("EMAIL_ROUTE_NOT_CONFIGURED");const template=getSystemTemplate(parsed.templateKey),variables=template.variablesSchema.parse(parsed.variables),now=new Date(),id=crypto.randomUUID(),payload=await this.cipher.encryptJson(variables,deliveryPayloadAad(parsed.siteId,id,template.key,template.version));const record:DeliveryInsert={id,siteId:parsed.siteId,purpose:parsed.purpose,templateKey:template.key,templateVersion:template.version,to:parsed.to,cc:parsed.cc??[],bcc:parsed.bcc??[],payload,idempotencyKey:parsed.idempotencyKey,maxAttempts:5,nextAttemptAt:now.toISOString(),createdByUserId:parsed.createdByUserId??null,createdAt:now.toISOString(),updatedAt:now.toISOString(),payloadPurgeAt:addDays(now,7),metadataPurgeAt:addDays(now,30)};const inserted=await this.repository.enqueueDelivery(record);return this.publish(inserted.delivery,inserted.created);}
  async processDelivery(siteId:string,deliveryId:string):Promise<Readonly<{terminal:boolean;retryAt?:string}>>{const now=new Date(),token=crypto.randomUUID();const delivery=await this.repository.claimDelivery(siteId,deliveryId,now.toISOString(),token,addMilliseconds(now,120_000));if(!delivery)return{terminal:true};if(!delivery.payload){await this.repository.completePermanentFailure(siteId,delivery.id,token,null,"EMAIL_PAYLOAD_PURGED","Delivery payload is unavailable",now.toISOString(),now.toISOString());return{terminal:true};}try{const template=getSystemTemplate(delivery.templateKey,delivery.templateVersion),variables=await this.cipher.decryptJson(delivery.payload,deliveryPayloadAad(siteId,delivery.id,delivery.templateKey,delivery.templateVersion),template.variablesSchema),rendered=template.render(variables);const connections=delivery.connectionId?[await this.mustConnection(siteId,delivery.connectionId)]:await this.repository.resolvePurposeConnections(siteId,delivery.purpose);if(connections.length===0)throw new Error("EMAIL_ROUTE_NOT_CONFIGURED");let last:ProviderSendOutcome|undefined,lastConnection:EmailConnection|undefined;for(const connection of connections){lastConnection=connection;const transport=await this.transport(siteId,connection);const started=new Date();last=await transport.send({deliveryId:delivery.id,from:connection.fromEmail,fromName:connection.fromName??undefined,replyTo:connection.replyToEmail??undefined,to:delivery.to,cc:delivery.cc,bcc:delivery.bcc,subject:rendered.subject,html:rendered.html,text:rendered.text});const finished=new Date();await this.repository.appendAttempt({id:crypto.randomUUID(),siteId,deliveryId:delivery.id,connectionId:connection.id,attemptNumber:delivery.attemptCount,outcome:last.kind,errorClass:"errorClass" in last?last.errorClass:null,errorCode:"code" in last?last.code:null,errorMessage:"message" in last?last.message:null,providerMessageId:"messageId" in last?last.messageId??null:null,providerResponse:"metadata" in last?last.metadata??null:null,latencyMs:finished.getTime()-started.getTime(),startedAt:started.toISOString(),finishedAt:finished.toISOString()});if(last.kind==="accepted"||last.kind==="queued_by_provider"){await this.repository.updateConnectionHealth(siteId,connection.id,"healthy");await this.repository.completeAccepted(siteId,delivery.id,token,last.kind,connection.id,last.messageId??null,rendered.subject,finished.toISOString());return{terminal:true};}if(last.kind==="transient_failure")break;}
      if(!last||!lastConnection)throw new Error("EMAIL_PROVIDER_FAILURE");if(last.kind==="transient_failure"&&delivery.attemptCount<delivery.maxAttempts){const delay=Math.min(30_000*2**(delivery.attemptCount-1),3_600_000),retryAt=addMilliseconds(now,delay);await this.repository.scheduleRetry(siteId,delivery.id,token,lastConnection.id,last.code,last.message,retryAt,new Date().toISOString());return{terminal:false,retryAt};}await this.repository.completePermanentFailure(siteId,delivery.id,token,lastConnection.id,"code" in last?last.code:"EMAIL_PROVIDER_FAILURE","message" in last?last.message:"Provider failed",new Date().toISOString(),addDays(now,7));return{terminal:true};
    }catch(error){await this.repository.completePermanentFailure(siteId,delivery.id,token,null,"EMAIL_PROCESSING_FAILED",safeMessage(error),new Date().toISOString(),addDays(now,7));return{terminal:true};}}
  async cancel(siteId:string,id:string):Promise<boolean>{return this.repository.cancelPending(siteId,id,new Date().toISOString());}
  async retry(siteId:string,id:string):Promise<EmailDelivery>{const delivery=await this.repository.retryFailed(siteId,id,new Date().toISOString());if(!delivery)throw new Error("EMAIL_DELIVERY_NOT_RETRYABLE");await this.publisher.publish({version:1,siteId,deliveryId:id});return delivery;}
  private async mustConnection(siteId:string,id:string):Promise<EmailConnection>{const connection=await this.repository.getConnection(siteId,id);if(!connection)throw new Error("EMAIL_CONNECTION_NOT_FOUND");return connection;}
  private async ensureDefaultRoutes(siteId:string,connectionId:string):Promise<void>{for(const purpose of EmailPurposeSchema.options){await this.repository.ensurePurposeRoute(siteId,purpose,connectionId);}}
  private async transport(siteId:string,connection:EmailConnection){let secret:unknown={};if(connection.provider!=="preview"){const envelope=await this.repository.getConnectionSecret(siteId,connection.id);if(!envelope)throw new Error("EMAIL_SECRET_UNAVAILABLE");secret=await this.cipher.decryptJson(envelope,connectionSecretAad(siteId,connection.id,connection.provider),secretSchema(connection.provider));}return createEmailProvider(connection,secret,this.runtime);}
  private async publish(delivery:EmailDelivery,created:boolean):Promise<EnqueueResult>{if(!created)return{delivery,created:false,wakeUpPending:false};try{await this.publisher.publish({version:1,siteId:delivery.siteId,deliveryId:delivery.id});return{delivery:(await this.repository.getDelivery(delivery.siteId,delivery.id))??delivery,created:true,wakeUpPending:false};}catch{return{delivery,created:true,wakeUpPending:true};}}
}

export function createEmailService(repository:EmailRepository,locals?:RuntimeLocals):EmailDeliveryService{const env=getCloudflareEnv(locals),queue=env.aria_email_queue;let service:EmailDeliveryService;const publisher:EmailQueuePublisher={async publish(message){if(queue){await queue.send(message);return;}if(env.aria_db)throw new Error("EMAIL_QUEUE_UNAVAILABLE");await service.processDelivery(message.siteId,message.deliveryId);}};const keyring={async getDefaultKey(){return repository.getOrCreateManagedKey(MANAGED_EMAIL_KEY_ID,randomKeyBase64());},async getKey(keyId:string){return repository.getManagedKey(keyId);}};service=new EmailDeliveryService(repository,new EmailSecretCipher(locals,keyring),publisher,env.aria_db?"cloudflare":"node");return service;}
