import type { CmsSearchDocument, CmsSearchResult } from "../schemas";
import { CmsSearchDocumentSchema, CmsSearchResultSchema } from "../schemas";
import type { CmsStorageExecutor } from "./executor";

type CmsSearchDocumentRow = { entity_type: "collection" | "entry"; entity_id: string; collection_id: string | null; locale: string; title: string; slug: string | null; collection_name: string | null; collection_label: string | null; status: "draft" | "published" | "scheduled" | "archived" | null; searchable_text: string; source_version: string; updated_at: string; rank?: number };
function mapCmsSearchDocumentRow(row: CmsSearchDocumentRow): CmsSearchDocument { return CmsSearchDocumentSchema.parse({ entityType: row.entity_type, entityId: row.entity_id, collectionId: row.collection_id, locale: row.locale, title: row.title, slug: row.slug, collectionName: row.collection_name, collectionLabel: row.collection_label, status: row.status, searchableText: row.searchable_text, sourceVersion: row.source_version, updatedAt: row.updated_at }); }
async function cmsUpsertSearchDocument(executor: CmsStorageExecutor, parsed: CmsSearchDocument, generation: string): Promise<void> { await executor.run(`INSERT INTO aria_cms_search_documents (entity_type, entity_id, collection_id, locale, title, slug, collection_name, collection_label, status, searchable_text, source_version, updated_at, generation) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT(entity_type, entity_id, locale, generation) DO UPDATE SET collection_id = excluded.collection_id, title = excluded.title, slug = excluded.slug, collection_name = excluded.collection_name, collection_label = excluded.collection_label, status = excluded.status, searchable_text = excluded.searchable_text, source_version = excluded.source_version, updated_at = excluded.updated_at, generation = excluded.generation WHERE excluded.updated_at > aria_cms_search_documents.updated_at OR (excluded.updated_at = aria_cms_search_documents.updated_at AND excluded.source_version >= aria_cms_search_documents.source_version)`, [parsed.entityType, parsed.entityId, parsed.collectionId, parsed.locale, parsed.title, parsed.slug, parsed.collectionName, parsed.collectionLabel, parsed.status, parsed.searchableText, parsed.sourceVersion, parsed.updatedAt, generation]); }
async function ensureCmsSearchScope(executor: CmsStorageExecutor, collectionId: string): Promise<void> { await executor.run(`INSERT OR IGNORE INTO aria_cms_search_scopes (collection_id, active_generation, pending_generation, updated_at) VALUES (?, 'default', NULL, ?)`, [collectionId, new Date().toISOString()]); }
export async function cmsGetSearchScopeGenerations(executor: CmsStorageExecutor, collectionId: string): Promise<string[]> { await ensureCmsSearchScope(executor, collectionId); const scope = await executor.queryFirst<{ active_generation: string; pending_generation: string | null }>(`SELECT active_generation, pending_generation FROM aria_cms_search_scopes WHERE collection_id = ?`, [collectionId]); return [scope?.active_generation ?? "default", scope?.pending_generation].filter((generation): generation is string => Boolean(generation)).filter((generation, index, all) => all.indexOf(generation) === index); }
export async function cmsReplaceSearchDocuments(executor: CmsStorageExecutor, documents: ReadonlyArray<CmsSearchDocument>): Promise<void> { for (const document of documents) { const parsed = CmsSearchDocumentSchema.parse(document); const collectionId = parsed.collectionId ?? parsed.entityId; for (const generation of await cmsGetSearchScopeGenerations(executor, collectionId)) await cmsUpsertSearchDocument(executor, parsed, generation); } }
export async function cmsBeginSearchScopeRebuild(executor: CmsStorageExecutor, options: { collectionId: string; generation: string }): Promise<boolean> { await ensureCmsSearchScope(executor, options.collectionId); await executor.run(`UPDATE aria_cms_search_scopes SET pending_generation = ?, updated_at = ? WHERE collection_id = ? AND pending_generation IS NULL`, [options.generation, new Date().toISOString(), options.collectionId]); const scope = await executor.queryFirst<{ pending_generation: string | null }>(`SELECT pending_generation FROM aria_cms_search_scopes WHERE collection_id = ?`, [options.collectionId]); return scope?.pending_generation === options.generation; }
export async function cmsWriteSearchScopeGeneration(executor: CmsStorageExecutor, options: { collectionId: string; generation: string; documents: ReadonlyArray<CmsSearchDocument> }): Promise<void> { for (const document of options.documents) { const parsed = CmsSearchDocumentSchema.parse(document); if ((parsed.collectionId ?? parsed.entityId) !== options.collectionId) throw new Error("CMS search scope document belongs to another collection"); await cmsUpsertSearchDocument(executor, parsed, options.generation); } }
export async function cmsCommitSearchScopeRebuild(executor: CmsStorageExecutor, options: { collectionId: string; generation: string }): Promise<boolean> { await executor.run(`UPDATE aria_cms_search_scopes SET active_generation = ?, pending_generation = NULL, updated_at = ? WHERE collection_id = ? AND pending_generation = ?`, [options.generation, new Date().toISOString(), options.collectionId, options.generation]); const scope = await executor.queryFirst<{ active_generation: string; pending_generation: string | null }>(`SELECT active_generation, pending_generation FROM aria_cms_search_scopes WHERE collection_id = ?`, [options.collectionId]); return scope?.active_generation === options.generation && scope.pending_generation === null; }
export async function cmsAbortSearchScopeRebuild(executor: CmsStorageExecutor, options: { collectionId: string; generation: string }): Promise<void> { await executor.run(`UPDATE aria_cms_search_scopes SET pending_generation = NULL, updated_at = ? WHERE collection_id = ? AND pending_generation = ?`, [new Date().toISOString(), options.collectionId, options.generation]); await executor.run(`DELETE FROM aria_cms_search_documents WHERE collection_id = ? AND generation = ?`, [options.collectionId, options.generation]); }
export async function cmsGetSearchDocumentStats(executor: CmsStorageExecutor): Promise<{ documents: number; collections: number; entries: number; expectedDocuments: number; expectedCollections: number; expectedEntries: number; missingDocuments: number; orphanedDocuments: number; staleDocuments: number; countsByScope: Array<{ entityType: CmsSearchDocument["entityType"]; collectionId: string; locale: string; documents: number }> }> {
  const row = await executor.queryFirst<{ documents: number; collections: number; entries: number }>(`SELECT COUNT(*) AS documents, SUM(CASE WHEN d.entity_type = 'collection' THEN 1 ELSE 0 END) AS collections, SUM(CASE WHEN d.entity_type = 'entry' THEN 1 ELSE 0 END) AS entries FROM aria_cms_search_documents d JOIN aria_cms_search_scopes s ON s.collection_id = d.collection_id AND s.active_generation = d.generation`);
  const expected = await executor.queryFirst<{ expected_collections: number; expected_entries: number }>(`SELECT (SELECT COUNT(*) FROM aria_collections) AS expected_collections, (SELECT COUNT(*) FROM aria_entry_locales) AS expected_entries`);
  const drift = await executor.queryFirst<{ missing_documents: number; orphaned_documents: number; stale_documents: number }>(`WITH active AS (SELECT d.* FROM aria_cms_search_documents d JOIN aria_cms_search_scopes s ON s.collection_id = d.collection_id AND s.active_generation = d.generation) SELECT ((SELECT COUNT(*) FROM aria_collections c LEFT JOIN active d ON d.entity_type = 'collection' AND d.entity_id = c.id AND d.locale = 'global' WHERE d.entity_id IS NULL) + (SELECT COUNT(*) FROM aria_entry_locales l LEFT JOIN active d ON d.entity_type = 'entry' AND d.entity_id = l.entry_id AND d.locale = l.locale WHERE d.entity_id IS NULL)) AS missing_documents, (SELECT COUNT(*) FROM active d LEFT JOIN aria_collections c ON d.entity_type = 'collection' AND c.id = d.entity_id LEFT JOIN aria_entry_locales l ON d.entity_type = 'entry' AND l.entry_id = d.entity_id AND l.locale = d.locale WHERE (d.entity_type = 'collection' AND c.id IS NULL) OR (d.entity_type = 'entry' AND l.entry_id IS NULL)) AS orphaned_documents, (SELECT COUNT(*) FROM active d LEFT JOIN aria_collections c ON d.entity_type = 'collection' AND c.id = d.entity_id LEFT JOIN aria_entries e ON d.entity_type = 'entry' AND e.id = d.entity_id LEFT JOIN aria_entry_locales l ON d.entity_type = 'entry' AND l.entry_id = d.entity_id AND l.locale = d.locale WHERE (d.entity_type = 'collection' AND c.id IS NOT NULL AND d.updated_at <> c.updated_at) OR (d.entity_type = 'entry' AND e.id IS NOT NULL AND l.entry_id IS NOT NULL AND (d.updated_at <> e.updated_at OR d.source_version <> (e.version || ':' || l.locale)))) AS stale_documents`);
  const scopeCounts = await executor.queryAll<{ entity_type: CmsSearchDocument["entityType"]; collection_id: string; locale: string; documents: number }>(`SELECT d.entity_type, d.collection_id, d.locale, COUNT(*) AS documents FROM aria_cms_search_documents d JOIN aria_cms_search_scopes s ON s.collection_id = d.collection_id AND s.active_generation = d.generation GROUP BY d.entity_type, d.collection_id, d.locale ORDER BY d.collection_id, d.locale, d.entity_type`);
  const expectedCollections = Number(expected?.expected_collections ?? 0); const expectedEntries = Number(expected?.expected_entries ?? 0);
  return { documents: Number(row?.documents ?? 0), collections: Number(row?.collections ?? 0), entries: Number(row?.entries ?? 0), expectedDocuments: expectedCollections + expectedEntries, expectedCollections, expectedEntries, missingDocuments: Number(drift?.missing_documents ?? 0), orphanedDocuments: Number(drift?.orphaned_documents ?? 0), staleDocuments: Number(drift?.stale_documents ?? 0), countsByScope: scopeCounts.map((scope) => ({ entityType: scope.entity_type, collectionId: scope.collection_id, locale: scope.locale, documents: Number(scope.documents) })) };
}
export async function cmsCleanupInactiveSearchScopeDocuments(executor: CmsStorageExecutor, collectionId: string): Promise<void> { await executor.run(`DELETE FROM aria_cms_search_documents WHERE collection_id = ? AND generation <> (SELECT active_generation FROM aria_cms_search_scopes WHERE collection_id = ?)`, [collectionId, collectionId]); }
export async function cmsDeleteSearchDocuments(executor: CmsStorageExecutor, options: { entityType?: CmsSearchDocument["entityType"]; entityId?: string; collectionId?: string; locale?: string }): Promise<void> { const clauses: string[] = []; const args: string[] = []; if (options.entityType) { clauses.push("entity_type = ?"); args.push(options.entityType); } if (options.entityId) { clauses.push("entity_id = ?"); args.push(options.entityId); } if (options.collectionId) { clauses.push("collection_id = ?"); args.push(options.collectionId); } if (options.locale) { clauses.push("locale = ?"); args.push(options.locale); } if (clauses.length === 0) throw new Error("At least one CMS search document filter is required"); await executor.run(`DELETE FROM aria_cms_search_documents WHERE ${clauses.join(" AND ")}`, args); }
function escapeSqlLike(value: string): string { return value.replace(/[\\%_]/g, "\\$&"); }
export async function cmsSearchCmsDocuments(executor: CmsStorageExecutor, options: { query: string; locales: readonly string[]; limit: number }): Promise<CmsSearchResult[]> { const query = options.query.trim().toLocaleLowerCase(); const locales = [...new Set(options.locales.map((locale) => locale.trim()))].filter(Boolean); if (!query || locales.length === 0) return []; const escaped = escapeSqlLike(query); const prefix = `${escaped}%`; const contains = `%${escaped}%`; const rows = await executor.queryAll<CmsSearchDocumentRow>(`SELECT d.entity_type, d.entity_id, d.collection_id, d.locale, d.title, d.slug, d.collection_name, d.collection_label, d.status, d.searchable_text, d.source_version, d.updated_at, CASE WHEN lower(d.title) = ? OR lower(COALESCE(d.slug, '')) = ? THEN 0 WHEN lower(d.title) LIKE ? ESCAPE '\\' OR lower(COALESCE(d.slug, '')) LIKE ? ESCAPE '\\' THEN 1 ELSE 2 END AS rank FROM aria_cms_search_documents d JOIN aria_cms_search_scopes s ON s.collection_id = d.collection_id AND s.active_generation = d.generation WHERE d.locale IN (${locales.map(() => "?").join(", ")}) AND (lower(d.title) LIKE ? ESCAPE '\\' OR lower(COALESCE(d.slug, '')) LIKE ? ESCAPE '\\' OR lower(d.searchable_text) LIKE ? ESCAPE '\\') ORDER BY rank ASC, d.updated_at DESC, d.entity_id ASC LIMIT ?`, [query, query, prefix, prefix, ...locales, contains, contains, contains, options.limit]); return rows.map((row) => CmsSearchResultSchema.parse({ ...mapCmsSearchDocumentRow(row), rank: row.rank ?? 2 })); }
