import type { CmsEntryWorkflow, CmsReviewAnnotation } from "../schemas";
import {
  CmsEntryWorkflowSchema,
  CmsReviewAnnotationSchema,
} from "../schemas";
import type { CmsStorageExecutor } from "./executor";

type CmsEntryWorkflowRow = { entry_id: string; locale: string; state: CmsEntryWorkflow["state"]; reviewed_version: string | null; assigned_to_id: string | null; updated_by_id: string; updated_at: string };
function mapCmsEntryWorkflow(row: CmsEntryWorkflowRow): CmsEntryWorkflow { return CmsEntryWorkflowSchema.parse({ entryId: row.entry_id, locale: row.locale, state: row.state, reviewedVersion: row.reviewed_version, assignedToId: row.assigned_to_id, updatedById: row.updated_by_id, updatedAt: row.updated_at }); }
export async function cmsGetEntryWorkflow(executor: CmsStorageExecutor, input: { entryId: string; locale: string }): Promise<CmsEntryWorkflow | null> { const row = await executor.queryFirst<CmsEntryWorkflowRow>(`SELECT * FROM aria_cms_entry_workflow WHERE entry_id = ? AND locale = ?`, [input.entryId, input.locale]); return row ? mapCmsEntryWorkflow(row) : null; }
export async function cmsSaveEntryWorkflow(executor: CmsStorageExecutor, input: CmsEntryWorkflow & { expectedState?: CmsEntryWorkflow["state"] | null }): Promise<CmsEntryWorkflow | null> {
  const parsed = CmsEntryWorkflowSchema.parse({ entryId: input.entryId, locale: input.locale, state: input.state, reviewedVersion: input.reviewedVersion, assignedToId: input.assignedToId, updatedById: input.updatedById, updatedAt: input.updatedAt });
  if (input.expectedState === null) await executor.run(`INSERT INTO aria_cms_entry_workflow (entry_id, locale, state, reviewed_version, assigned_to_id, updated_by_id, updated_at) SELECT ?, ?, ?, ?, ?, ?, ? WHERE NOT EXISTS (SELECT 1 FROM aria_cms_entry_workflow WHERE entry_id = ? AND locale = ?)`, [parsed.entryId, parsed.locale, parsed.state, parsed.reviewedVersion, parsed.assignedToId, parsed.updatedById, parsed.updatedAt, parsed.entryId, parsed.locale]);
  else await executor.run(`UPDATE aria_cms_entry_workflow SET state = ?, reviewed_version = ?, assigned_to_id = ?, updated_by_id = ?, updated_at = ? WHERE entry_id = ? AND locale = ? AND state = ?`, [parsed.state, parsed.reviewedVersion, parsed.assignedToId, parsed.updatedById, parsed.updatedAt, parsed.entryId, parsed.locale, input.expectedState ?? "none"]);
  const saved = await cmsGetEntryWorkflow(executor, parsed);
  return saved?.updatedAt === parsed.updatedAt && saved.updatedById === parsed.updatedById ? saved : null;
}

type CmsReviewAnnotationRow = { id: string; resource_type: CmsReviewAnnotation["resourceType"]; resource_id: string; collection_id: string | null; locale: string | null; field_path: string | null; anchor_json: string | null; fallback_label: string | null; body: string; status: CmsReviewAnnotation["status"]; author_id: string; resolved_by_id: string | null; resolved_at: string | null; created_at: string; updated_at: string };
function mapCmsReviewAnnotation(row: CmsReviewAnnotationRow): CmsReviewAnnotation { return CmsReviewAnnotationSchema.parse({ id: row.id, resourceType: row.resource_type, resourceId: row.resource_id, collectionId: row.collection_id, locale: row.locale, fieldPath: row.field_path, anchor: row.anchor_json ? JSON.parse(row.anchor_json) : null, fallbackLabel: row.fallback_label, body: row.body, status: row.status, authorId: row.author_id, resolvedById: row.resolved_by_id, resolvedAt: row.resolved_at, createdAt: row.created_at, updatedAt: row.updated_at }); }
export async function cmsListReviewAnnotations(executor: CmsStorageExecutor, input: { resourceType: CmsReviewAnnotation["resourceType"]; resourceId: string; locale?: string; status?: CmsReviewAnnotation["status"] }): Promise<CmsReviewAnnotation[]> { const filters = ["resource_type = ?", "resource_id = ?"]; const args: unknown[] = [input.resourceType, input.resourceId]; if (input.locale) { filters.push("locale = ?"); args.push(input.locale); } if (input.status) { filters.push("status = ?"); args.push(input.status); } const rows = await executor.queryAll<CmsReviewAnnotationRow>(`SELECT * FROM aria_cms_review_annotations WHERE ${filters.join(" AND ")} ORDER BY created_at ASC, id ASC`, args); return rows.map(mapCmsReviewAnnotation); }
export async function cmsCreateReviewAnnotation(executor: CmsStorageExecutor, annotation: CmsReviewAnnotation): Promise<CmsReviewAnnotation> { const parsed = CmsReviewAnnotationSchema.parse(annotation); await executor.run(`INSERT INTO aria_cms_review_annotations (id, resource_type, resource_id, collection_id, locale, field_path, anchor_json, fallback_label, body, status, author_id, resolved_by_id, resolved_at, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`, [parsed.id, parsed.resourceType, parsed.resourceId, parsed.collectionId, parsed.locale, parsed.fieldPath, parsed.anchor ? JSON.stringify(parsed.anchor) : null, parsed.fallbackLabel, parsed.body, parsed.status, parsed.authorId, parsed.resolvedById, parsed.resolvedAt, parsed.createdAt, parsed.updatedAt]); return parsed; }
export async function cmsResolveReviewAnnotation(executor: CmsStorageExecutor, input: { id: string; resourceType: CmsReviewAnnotation["resourceType"]; resourceId: string; actorId: string; updatedAt: string }): Promise<CmsReviewAnnotation | null> { await executor.run(`UPDATE aria_cms_review_annotations SET status = 'resolved', resolved_by_id = ?, resolved_at = ?, updated_at = ? WHERE id = ? AND resource_type = ? AND resource_id = ? AND status = 'open'`, [input.actorId, input.updatedAt, input.updatedAt, input.id, input.resourceType, input.resourceId]); const row = await executor.queryFirst<CmsReviewAnnotationRow>(`SELECT * FROM aria_cms_review_annotations WHERE id = ? AND resource_type = ? AND resource_id = ? AND status = 'resolved' AND updated_at = ?`, [input.id, input.resourceType, input.resourceId, input.updatedAt]); return row ? mapCmsReviewAnnotation(row) : null; }
export async function cmsReopenReviewAnnotation(executor: CmsStorageExecutor, input: { id: string; resourceType: CmsReviewAnnotation["resourceType"]; resourceId: string; actorId: string; updatedAt: string }): Promise<CmsReviewAnnotation | null> { await executor.run(`UPDATE aria_cms_review_annotations SET status = 'open', resolved_by_id = NULL, resolved_at = NULL, updated_at = ? WHERE id = ? AND resource_type = ? AND resource_id = ? AND status = 'resolved'`, [input.updatedAt, input.id, input.resourceType, input.resourceId]); const row = await executor.queryFirst<CmsReviewAnnotationRow>(`SELECT * FROM aria_cms_review_annotations WHERE id = ? AND resource_type = ? AND resource_id = ? AND status = 'open' AND updated_at = ?`, [input.id, input.resourceType, input.resourceId, input.updatedAt]); return row ? mapCmsReviewAnnotation(row) : null; }
