import { z } from "zod";
import { asSchema } from "ai";
import {
  AriaApplyDesignSystemPatchInputSchema,
  AriaApplyDesignSystemTemplateInputSchema,
  AriaApplyClassToNodesInputSchema,
  AriaArchiveEntryInputSchema,
  AriaAttachMediaInputSchema,
  AriaBindNodeFieldInputSchema,
  AriaClearCollectionTemplateInputSchema,
  AriaCompareEntryRevisionsInputSchema,
  AriaCreateReviewAnnotationInputSchema,
  AriaCreateClassInputSchema,
  AriaCreateCollectionInputSchema,
  AriaCreateEntryInputSchema,
  AriaCreatePageInputSchema,
  AriaCreateLayoutInputSchema,
  AriaCreateComponentInputSchema,
  AriaDuplicateDocumentInputSchema,
  AriaPageSlugInputSchema,
  AriaUpdateLayoutSlotsInputSchema,
  AriaUpdateNodeClassesInputSchema,
  AriaReplaceNodeInputSchema,
  AriaGetSiteSettingsInputSchema,
  AriaGetLocalizationSettingsInputSchema,
  AriaUpdateLocalizationSettingsInputSchema,
  AriaGetEntryTranslationContextInputSchema,
  AriaSaveEntryTranslationInputSchema,
  AriaUpdateSiteSettingsInputSchema,
  AriaUpdateDiscoverySettingsInputSchema,
  AriaUpdateAppearanceInputSchema,
  AriaUpdateIconPacksInputSchema,
  AriaListRedirectsInputSchema,
  AriaCreateRedirectInputSchema,
  AriaUpdateRedirectInputSchema,
  AriaDeleteRedirectInputSchema,
  AriaDeleteMediaInputSchema,
  AriaRenameMediaInputSchema,
  AriaDuplicateMediaInputSchema,
  AriaGetMediaUsagesInputSchema,
  AriaSetPageCoverInputSchema,
  AriaImportMediaFromUrlInputSchema,
  AriaUpdateClassPseudoRuleInputSchema,
  AriaDeleteCustomFontInputSchema,
  AriaRenameCustomFontInputSchema,
  AriaUpdateGoogleFontVariantsInputSchema,
  AriaDeleteClassInputSchema,
  AriaDeleteCollectionInputSchema,
  AriaDeleteDocumentInputSchema,
  AriaDeleteEntryInputSchema,
  AriaDeleteNodeInputSchema,
  AriaDisableFontInputSchema,
  AriaDuplicateEntryInputSchema,
  AriaDuplicateClassInputSchema,
  AriaEnableGoogleFontInputSchema,
  AriaGetCmsInventoryInputSchema,
  AriaGetCollectionInputSchema,
  AriaGetDesignSystemInputSchema,
  AriaGetDiscoveryArtifactsInputSchema,
  AriaGetDiscoveryBaselineInputSchema,
  AriaGetDiscoveryReportInputSchema,
  AriaGetAnalyticsAvailabilityInputSchema,
  AriaGetPageTrafficInputSchema,
  AriaGetPageVersionInputSchema,
  AriaGetPagesTrafficInputSchema,
  AriaGetSiteTrafficInputSchema,
  AriaGetTrafficSummaryInputSchema,
  AriaGetEntryInputSchema,
  AriaGetEntryReviewInputSchema,
  AriaGetEntryRevisionInputSchema,
  AriaGetSiteContextInputSchema,
  AriaGetFontConfigInputSchema,
  AriaInsertNodesInputSchema,
  AriaListClassesInputSchema,
  AriaListCollectionsInputSchema,
  AriaListEntriesInputSchema,
  AriaListEntryRevisionsInputSchema,
  AriaListReviewAnnotationsInputSchema,
  AriaListFontsInputSchema,
  AriaListMediaInputSchema,
  AriaListPageVersionsInputSchema,
  AriaManageCssVariablesInputSchema,
  AriaMoveNodeInputSchema,
  AriaMutateNodeInputSchema,
  AriaPublishEntryInputSchema,
  AriaPublishPageInputSchema,
  AriaPreviewDesignSystemPatchInputSchema,
  AriaQueryEntriesInputSchema,
  AriaReadComponentInputSchema,
  AriaReadLayoutInputSchema,
  AriaReadPageInputSchema,
  AriaRegenerateGlobalCssInputSchema,
  AriaRemoveClassRuleInputSchema,
  AriaRenameClassInputSchema,
  AriaSaveDesignSystemBreakpointsInputSchema,
  AriaSaveDesignSystemColorsInputSchema,
  AriaSaveDesignSystemGlobalStylesInputSchema,
  AriaSaveDesignSystemTypographyInputSchema,
  AriaSaveDocumentInputSchema,
  AriaSetDesignSystemPrimaryColorInputSchema,
  AriaSetCollectionTemplateInputSchema,
  AriaSetContainerLoopInputSchema,
  AriaSetupBlogInputSchema,
  AriaSetupConfigCollectionInputSchema,
  AriaSetupNavCollectionInputSchema,
  AriaSetupTagArchiveInputSchema,
  AriaRestoreEntryRevisionInputSchema,
  AriaReopenReviewAnnotationInputSchema,
  AriaResolveReviewAnnotationInputSchema,
  AriaUnpublishEntryInputSchema,
  AriaUpdateNodeMotionInputSchema,
  AriaUpdateClassRuleInputSchema,
  AriaUpdateCollectionInputSchema,
  AriaUpdateEntryInputSchema,
  AriaUpdateEntryReviewInputSchema,
  AriaUpdatePageMetaInputSchema,
  AriaUpdatePageSeoInputSchema,
  AriaCheckLibraryUpdatesInputSchema,
  AriaCreateSiteExportInputSchema,
  AriaDeleteSiteExportInputSchema,
  AriaGetLatestSiteExportInputSchema,
  AriaInstallLibraryComponentInputSchema,
  AriaInstallLibraryPackInputSchema,
  AriaListInstalledLibraryPacksInputSchema,
  AriaListSiteExportsInputSchema,
  AriaSearchLibraryInputSchema,
  AriaUninstallLibraryPackInputSchema,
  AriaApplyContentSyncInputSchema,
  AriaGetContentSyncStatusInputSchema,
  AriaListContentSyncHistoryInputSchema,
  AriaPlanContentSyncInputSchema,
  AriaApplyMediaSyncInputSchema,
  AriaDeleteMediaTransformVariantInputSchema,
  AriaGetMediaTransformStateInputSchema,
  AriaListMediaSyncHistoryInputSchema,
  AriaPlanMediaSyncInputSchema,
  AriaRebuildMediaUsageIndexInputSchema,
  AriaSaveMediaProfileInputSchema,
  AriaSaveMediaTransformVariantInputSchema,
  AriaGetCacheObservabilityInputSchema,
  AriaGetCacheStatsInputSchema,
  AriaGetSystemStatusInputSchema,
  AriaListUsersInputSchema,
  AriaGetEmailOutboxOverviewInputSchema,
  AriaListEmailConnectionsInputSchema,
  AriaListEmailDeliveriesInputSchema,
  AriaListEmailRoutesInputSchema,
  AriaGetAuthMethodsConfigInputSchema,
  AriaGetPlatformInfoInputSchema,
  AriaGetPlatformMetricsInputSchema,
  AriaGetTwoFactorPolicyInputSchema,
} from "../schemas";
import type { ServerToolName } from "../tools/constants";

const EmptyInputSchema = z.object({}).strict();

/** Canonical input schema inventory for every executable server command. */
export const SERVER_TOOL_INPUT_ZOD_SCHEMAS = {
  aria_get_site_context: AriaGetSiteContextInputSchema,
  aria_get_discovery_report: AriaGetDiscoveryReportInputSchema,
  aria_get_discovery_artifacts: AriaGetDiscoveryArtifactsInputSchema,
  aria_get_discovery_baseline: AriaGetDiscoveryBaselineInputSchema,
  aria_get_analytics_availability: AriaGetAnalyticsAvailabilityInputSchema,
  aria_get_traffic_summary: AriaGetTrafficSummaryInputSchema,
  aria_get_site_traffic: AriaGetSiteTrafficInputSchema,
  aria_get_pages_traffic: AriaGetPagesTrafficInputSchema,
  aria_get_page_traffic: AriaGetPageTrafficInputSchema,
  aria_get_site_settings: AriaGetSiteSettingsInputSchema,
  aria_get_localization_settings: AriaGetLocalizationSettingsInputSchema,
  aria_list_redirects: AriaListRedirectsInputSchema,
  aria_list_media: AriaListMediaInputSchema,
  aria_get_media_usages: AriaGetMediaUsagesInputSchema,
  aria_get_media_transform_state: AriaGetMediaTransformStateInputSchema,
  aria_list_media_sync_history: AriaListMediaSyncHistoryInputSchema,
  aria_list_pages: EmptyInputSchema,
  aria_read_page: AriaReadPageInputSchema,
  aria_list_page_versions: AriaListPageVersionsInputSchema,
  aria_get_page_version: AriaGetPageVersionInputSchema,
  aria_search_library: AriaSearchLibraryInputSchema,
  aria_list_installed_library_packs: AriaListInstalledLibraryPacksInputSchema,
  aria_check_library_updates: AriaCheckLibraryUpdatesInputSchema,
  aria_list_site_exports: AriaListSiteExportsInputSchema,
  aria_get_latest_site_export: AriaGetLatestSiteExportInputSchema,
  aria_get_content_sync_status: AriaGetContentSyncStatusInputSchema,
  aria_list_content_sync_history: AriaListContentSyncHistoryInputSchema,
  aria_list_components: EmptyInputSchema,
  aria_read_component: AriaReadComponentInputSchema,
  aria_list_layouts: EmptyInputSchema,
  aria_read_layout: AriaReadLayoutInputSchema,
  aria_get_design_system: AriaGetDesignSystemInputSchema,
  aria_preview_design_system_patch: AriaPreviewDesignSystemPatchInputSchema,
  aria_list_element_types: EmptyInputSchema,
  aria_get_node_capabilities: EmptyInputSchema,
  aria_list_fonts: AriaListFontsInputSchema,
  aria_get_font_config: AriaGetFontConfigInputSchema,
  aria_list_classes: AriaListClassesInputSchema,
  aria_get_cms_inventory: AriaGetCmsInventoryInputSchema,
  aria_list_collections: AriaListCollectionsInputSchema,
  aria_get_collection: AriaGetCollectionInputSchema,
  aria_list_entries: AriaListEntriesInputSchema,
  aria_get_entry: AriaGetEntryInputSchema,
  aria_get_entry_translation_context: AriaGetEntryTranslationContextInputSchema,
  aria_query_entries: AriaQueryEntriesInputSchema,
  aria_list_entry_revisions: AriaListEntryRevisionsInputSchema,
  aria_get_entry_revision: AriaGetEntryRevisionInputSchema,
  aria_compare_entry_revisions: AriaCompareEntryRevisionsInputSchema,
  aria_get_entry_review: AriaGetEntryReviewInputSchema,
  aria_list_review_annotations: AriaListReviewAnnotationsInputSchema,
  aria_apply_design_system_patch: AriaApplyDesignSystemPatchInputSchema,
  aria_set_design_system_primary_color:
    AriaSetDesignSystemPrimaryColorInputSchema,
  aria_save_design_system_colors: AriaSaveDesignSystemColorsInputSchema,
  aria_save_design_system_typography: AriaSaveDesignSystemTypographyInputSchema,
  aria_save_design_system_global_styles:
    AriaSaveDesignSystemGlobalStylesInputSchema,
  aria_save_design_system_breakpoints:
    AriaSaveDesignSystemBreakpointsInputSchema,
  aria_apply_design_system_template: AriaApplyDesignSystemTemplateInputSchema,
  aria_update_site_settings: AriaUpdateSiteSettingsInputSchema,
  aria_update_localization_settings: AriaUpdateLocalizationSettingsInputSchema,
  aria_update_discovery_settings: AriaUpdateDiscoverySettingsInputSchema,
  aria_update_appearance: AriaUpdateAppearanceInputSchema,
  aria_update_icon_packs: AriaUpdateIconPacksInputSchema,
  aria_create_page: AriaCreatePageInputSchema,
  aria_install_library_pack: AriaInstallLibraryPackInputSchema,
  aria_install_library_component: AriaInstallLibraryComponentInputSchema,
  aria_uninstall_library_pack: AriaUninstallLibraryPackInputSchema,
  aria_create_site_export: AriaCreateSiteExportInputSchema,
  aria_delete_site_export: AriaDeleteSiteExportInputSchema,
  aria_plan_content_sync: AriaPlanContentSyncInputSchema,
  aria_apply_content_sync: AriaApplyContentSyncInputSchema,
  aria_create_layout: AriaCreateLayoutInputSchema,
  aria_create_component: AriaCreateComponentInputSchema,
  aria_duplicate_document: AriaDuplicateDocumentInputSchema,
  aria_save_document: AriaSaveDocumentInputSchema,
  aria_delete_document: AriaDeleteDocumentInputSchema,
  aria_update_page_meta: AriaUpdatePageMetaInputSchema,
  aria_update_page_seo: AriaUpdatePageSeoInputSchema,
  aria_insert_nodes: AriaInsertNodesInputSchema,
  aria_mutate_node: AriaMutateNodeInputSchema,
  aria_update_node_motion: AriaUpdateNodeMotionInputSchema,
  aria_update_node_classes: AriaUpdateNodeClassesInputSchema,
  aria_replace_node: AriaReplaceNodeInputSchema,
  aria_move_node: AriaMoveNodeInputSchema,
  aria_delete_node: AriaDeleteNodeInputSchema,
  aria_update_layout_slots: AriaUpdateLayoutSlotsInputSchema,
  aria_attach_media_to_node: AriaAttachMediaInputSchema,
  aria_delete_media: AriaDeleteMediaInputSchema,
  aria_rename_media: AriaRenameMediaInputSchema,
  aria_duplicate_media: AriaDuplicateMediaInputSchema,
  aria_import_media_from_url: AriaImportMediaFromUrlInputSchema,
  aria_set_page_cover: AriaSetPageCoverInputSchema,
  aria_save_media_profile: AriaSaveMediaProfileInputSchema,
  aria_save_media_transform_variant: AriaSaveMediaTransformVariantInputSchema,
  aria_delete_media_transform_variant:
    AriaDeleteMediaTransformVariantInputSchema,
  aria_rebuild_media_usage_index: AriaRebuildMediaUsageIndexInputSchema,
  aria_plan_media_sync: AriaPlanMediaSyncInputSchema,
  aria_apply_media_sync: AriaApplyMediaSyncInputSchema,
  aria_create_redirect: AriaCreateRedirectInputSchema,
  aria_update_redirect: AriaUpdateRedirectInputSchema,
  aria_delete_redirect: AriaDeleteRedirectInputSchema,
  aria_create_collection: AriaCreateCollectionInputSchema,
  aria_update_entry_review: AriaUpdateEntryReviewInputSchema,
  aria_create_review_annotation: AriaCreateReviewAnnotationInputSchema,
  aria_resolve_review_annotation: AriaResolveReviewAnnotationInputSchema,
  aria_reopen_review_annotation: AriaReopenReviewAnnotationInputSchema,
  aria_update_collection: AriaUpdateCollectionInputSchema,
  aria_set_collection_template: AriaSetCollectionTemplateInputSchema,
  aria_clear_collection_template: AriaClearCollectionTemplateInputSchema,
  aria_delete_collection: AriaDeleteCollectionInputSchema,
  aria_create_entry: AriaCreateEntryInputSchema,
  aria_update_entry: AriaUpdateEntryInputSchema,
  aria_save_entry_translation: AriaSaveEntryTranslationInputSchema,
  aria_duplicate_entry: AriaDuplicateEntryInputSchema,
  aria_delete_entry: AriaDeleteEntryInputSchema,
  aria_restore_entry_revision: AriaRestoreEntryRevisionInputSchema,
  aria_bind_node_field: AriaBindNodeFieldInputSchema,
  aria_set_container_loop: AriaSetContainerLoopInputSchema,
  aria_setup_blog: AriaSetupBlogInputSchema,
  aria_setup_tag_archive: AriaSetupTagArchiveInputSchema,
  aria_setup_nav_collection: AriaSetupNavCollectionInputSchema,
  aria_setup_config_collection: AriaSetupConfigCollectionInputSchema,
  aria_create_class: AriaCreateClassInputSchema,
  aria_update_class_rule: AriaUpdateClassRuleInputSchema,
  aria_remove_class_rule: AriaRemoveClassRuleInputSchema,
  aria_delete_class: AriaDeleteClassInputSchema,
  aria_rename_class: AriaRenameClassInputSchema,
  aria_duplicate_class: AriaDuplicateClassInputSchema,
  aria_apply_class_to_nodes: AriaApplyClassToNodesInputSchema,
  aria_update_class_pseudo_rule: AriaUpdateClassPseudoRuleInputSchema,
  aria_manage_css_variables: AriaManageCssVariablesInputSchema,
  aria_regenerate_global_css: AriaRegenerateGlobalCssInputSchema,
  aria_enable_google_font: AriaEnableGoogleFontInputSchema,
  aria_disable_font: AriaDisableFontInputSchema,
  aria_delete_custom_font: AriaDeleteCustomFontInputSchema,
  aria_rename_custom_font: AriaRenameCustomFontInputSchema,
  aria_update_google_font_variants: AriaUpdateGoogleFontVariantsInputSchema,
  aria_publish_page: AriaPublishPageInputSchema,
  aria_unpublish_page: AriaPageSlugInputSchema,
  aria_archive_page: AriaPageSlugInputSchema,
  aria_unarchive_page: AriaPageSlugInputSchema,
  aria_publish_entry: AriaPublishEntryInputSchema,
  aria_unpublish_entry: AriaUnpublishEntryInputSchema,
  aria_archive_entry: AriaArchiveEntryInputSchema,
  aria_get_system_status: AriaGetSystemStatusInputSchema,
  aria_get_cache_stats: AriaGetCacheStatsInputSchema,
  aria_get_cache_observability: AriaGetCacheObservabilityInputSchema,
  aria_list_users: AriaListUsersInputSchema,
  aria_list_email_connections: AriaListEmailConnectionsInputSchema,
  aria_list_email_routes: AriaListEmailRoutesInputSchema,
  aria_get_email_outbox_overview: AriaGetEmailOutboxOverviewInputSchema,
  aria_list_email_deliveries: AriaListEmailDeliveriesInputSchema,
  aria_get_auth_methods_config: AriaGetAuthMethodsConfigInputSchema,
  aria_get_two_factor_policy: AriaGetTwoFactorPolicyInputSchema,
  aria_get_platform_info: AriaGetPlatformInfoInputSchema,
  aria_get_platform_metrics: AriaGetPlatformMetricsInputSchema,
} as const satisfies Record<ServerToolName, z.ZodType>;

export function getServerToolInputJsonSchema(
  toolName: ServerToolName,
): Record<string, unknown> {
  const inputSchema = SERVER_TOOL_INPUT_ZOD_SCHEMAS[
    toolName
  ] as z.ZodType<unknown>;
  const jsonSchema = asSchema<unknown>(inputSchema).jsonSchema;
  if (jsonSchema instanceof Promise) {
    throw new Error(
      `Server tool schema must resolve synchronously: ${toolName}`,
    );
  }
  return jsonSchema as Record<string, unknown>;
}
